### ISSUE TITLE
WeLoveIconFonts

### ISSUE THREAD

**Issue by Haroenv** [mrzmyr/awesome-icons#2]
http://weloveiconfonts.com/ could be added

**Comment by mrzmyr** [comment]
Thats not a specific font, right ?

**Comment by Haroenv** [comment]
Nope, but it is a resource to find iconfonts 

Cc @timpietrusky

**Comment by mrzmyr** [comment]
Can you add a description for it ? :)

**Comment by Haroenv** [comment]
"a free & open source icon fonts hosting service (like Google Web Fonts, but icon fonts only). " or something like that?
